services:
  # Servicio de Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "9000:80"
    volumes:
      # Montamos el proyecto local en /var/www/html
      - .:/var/www/html
    environment:
      # Variables de entorno para configurar tu .env
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: david
      DB_PASSWORD: 1234
    depends_on:
      - db

  # Servicio de MySQL
  db:
    image: mysql:latest
    container_name: laravel-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: david
      MYSQL_PASSWORD: 1234
    volumes:
      - dbdata:/var/lib/mysql

  # Servicio de phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel-phpmyadmin
    restart: always
    ports:
      - "9001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata:
